Repository desk-design-system/d2s, pull requests merged in 2023-06, with the labels that each got.

#98 Bugfix/fe fixes by arslan
  src/App.vue
  src/components/select/index.vue
Labels: bug

#97 handled dom click
  src/App.vue
  src/components/table/index.vue
Labels: Improvement

#99 append complete functionality of dropdown inside the index.vue file
  src/components/select/index.vue
Labels: bug

#101 requirement implementation
  src/App.vue
  src/components/table/Table.stories.js
  src/components/table/index.vue
Labels: Improvement

#102 feature: created tooltip component
  src/components/tooltip/Tooltip.stories.js
  src/components/tooltip/index.vue
Labels: New Feature

#105 Bugfix/fixes by arslan
  src/components/badges/index.vue
  src/components/select/index.vue
Labels: Improvement

#108 fix: select story file updated
  src/components/select/Select.stories.js
Labels: bug

#109 Table component d2s
  src/App.vue
  src/components/checkbox/index.vue
  src/components/icons/Selector.vue
  src/components/icons/SelectorDown.vue
  src/components/icons/SelectorUp.vue
  src/components/input/index.vue
  src/components/table/index.vue
Labels: Improvement

#110 feat:accordion
  src/components/Accordion/accordion.stories.js
  src/components/Accordion/index.vue
  src/components/AccordionTab/AccordionTab.stories.js
  src/components/AccordionTab/index.vue
  src/components/components.js
Labels: New Feature

#112 drawer size convert to string
  src/components/drawer/Drawer.stories.js
  src/components/drawer/index.vue
Labels: Improvement

#113 Feature/accordion junaidjahan
  src/components/Accordion/accordion.stories.js
  src/components/AccordionTab/AccordionTab.stories.js
Labels: bug

#114 Feature/accordion junaidjahan
  src/components/input/index.vue
  src/components/textarea/index.vue
Labels: New Feature

#115 Feature/textarea(events) junaidjahan
  src/components/input/index.vue
  src/components/textarea/Textarea.stories.js
  src/components/textarea/index.vue
Labels: Improvement

#117 Table component remerged
  src/App.vue
  src/components/checkbox/index.vue
  src/components/components.js
  src/components/table/Table.stories.js
  src/components/table/hoverRow.vue
  src/components/table/index.vue
  yarn.lock
Labels: Improvement

#124 Table changes
  src/App.vue
  src/components/input/index.vue
  src/components/table/Table.stories.js
  src/components/table/index.vue
Labels: Improvement

#131 Table row actions
  package-lock.json
  package.json
  src/App.vue
  src/components/dropdown/index.vue
  src/components/icons/GripVerticle.vue
  src/components/icons/Pencil.vue
  src/components/icons/Trash.vue
  src/components/table/Table.stories.js
  src/components/table/hoverRow.vue
  src/components/table/index.vue
  yarn.lock
Labels: Improvement

#130 Feature/icons junaidjahan
  src/components/checkbox/index.vue
  src/components/icons/Camera.vue
  src/components/icons/GameController.vue
  src/components/icons/Hammer.vue
  src/components/icons/HomeBuilding.vue
  src/components/icons/Remote.vue
  src/components/icons/TV.vue
  src/components/icons/Toolkit.vue
Labels: New Feature

#132 styling fixes
  src/App.vue
  src/components/table/Table.stories.js
  src/components/table/index.vue
Labels: Improvement
