Repository desk-design-system/d2s, pull requests merged in 2023-09, with the labels that each got.

#231 fix: add loop on children accordion-tab
  src/components/Accordion/index.vue
Labels: bug, Improvement

#234 done
  src/components/buttons/index.vue
Labels: Improvement

#233 Fix/accordion loop junaidjahan
  src/components/Telinput/index.vue
  src/components/textarea/index.vue
Labels: Improvement

#232 tag adder completed
  src/components/Accordion/index.vue
  src/components/badges/Badges.stories.js
  src/components/badges/index.vue
Labels: Improvement

#230 Usign form element
  src/App.vue
  src/components/Accordion/index.vue
  src/components/FormElement/FormElement.stories.js
  src/components/FormElement/index.vue
  src/components/alerts/Alert.stories.js
  src/components/autosearch/Autosearch.stories.js
  src/components/autosearch/index.vue
  src/components/checkbox/index.vue
  src/components/input/Input.stories.js
  src/components/input/index.vue
  src/components/textarea/index.vue
Labels: Improvement

#235 fix(table): unselected check box
  src/components/table/index.vue
Labels: bug, Improvement

#236 fix(accordion) : loop issue fixed
  src/components/Accordion/index.vue
Labels: bug, Improvement

#238 Fix/checkbox default prop
  src/components/FormElement/index.vue
  src/components/checkbox/index.vue
  src/components/input/index.vue
Labels: Improvement

#237 table row disable padding issue fixed
  src/components/table/index.vue
Labels: Complete

#240 feat: number input
  src/components/components.js
  src/components/icons/Minus.vue
  src/components/input-number/index.vue
  src/components/input/index.vue
Labels: New Feature, Complete

#239 New select comp
  src/components/badges/index.vue
  src/components/select/Select.stories.js
  src/components/select/index.vue
Labels: Improvement

#241 improvement: multi-select added in select
  src/components/select/index.vue
Labels: Improvement

#244 feature/multi-select
  src/components/badges/index.vue
  src/components/checkbox/index.vue
  src/components/select/index.vue
Labels: bug, Improvement

#247 fix: select v-model issue and number input
  src/components/Accordion/index.vue
  src/components/Telinput/index.vue
  src/components/input-number/index.vue
  src/components/select/index.vue
Labels: Improvement

#250 add offSet
  src/components/notification/Notification.stories.js
  src/components/notification/index.js
  src/components/notification/notificationUI.vue
Labels: Improvement

#251 feat: add new select and checkbox issues
  package.json
  src/components/Accordion/index.vue
  src/components/checkbox/index.vue
  src/components/components.js
  src/components/input-number/input-number.stories.js
  src/components/new-select/composables/index.js
  src/components/new-select/index.vue
  src/components/table/index.vue
  src/directives/index.js
  src/directives/on-click-outside/index.js
  src/directives/remove-focus/index.js
  src/main.js
  yarn.lock
Labels: Improvement
