Repository desk-design-system/d2s, pull requests merged in 2023-05, with the labels that each got.

#48 The kamil hayyat password pin eye bug fix
  src/assets/base.css
  src/components/input/Input.stories.js
  src/components/input/index.vue
Labels: bug

#49 The kamil hayyat auto search
  package.json
  src/components/components.js
Labels: New Feature

#61 stepper
  src/App.vue
  src/assets/index.css
  src/components/card/index.vue
  src/components/components.js
  src/components/stepper/Stepper.stories.js
  src/components/stepper/index.vue
Labels: New Feature

#62 Junaidjahan stepper
  src/App.vue
  src/assets/index.css
  src/components/card/index.vue
  src/components/stepper/index.vue
Labels: Improvement

#66 pagination-component
  src/App.vue
  src/components/Pagination/Pagination.stories.js
  src/components/Pagination/index.vue
  src/components/components.js
Labels: New Feature

#69 Junaidjahan textarea
  src/App.vue
  src/assets/index.css
  src/components/Telinput/index.vue
  src/components/card/index.vue
  src/components/icons/CalendarTimer.vue
  src/components/icons/CallDialing.vue
  src/components/icons/Controller.vue
  src/components/icons/Diamond.vue
  src/components/icons/Drone.vue
  src/components/icons/HorizontalDotsCircle.vue
  src/components/icons/Tablet.vue
  src/components/icons/WristWatch.vue
  src/components/input/index.vue
  src/components/stepper/index.vue
  src/components/textarea/Textarea.stories.js
  src/components/textarea/index.vue
Labels: New Feature

#70 Junaidjahan fix
  src/components/card/index.vue
Labels: bug

#76 pagination-fixes
  src/components/Pagination/index.vue
Labels: bug

#75 filterable-select
  src/App.vue
  src/components/select/Select.stories.js
  src/components/select/index.vue
Labels: Improvement

#74 Junaidjahan table nodata
  src/components/card/index.vue
  src/components/table/index.vue
Labels: Improvement

#77 fixes/select
  src/App.vue
  src/components/select/index.vue
Labels: bug

#78 select-fixes
  src/App.vue
  src/components/select/Select.stories.js
  src/components/select/index.vue
Labels: bug

#81 fix: select dropdown open/close issue and filterable checked issue is fixed
  src/components/select/index.vue
Labels: bug

#80 Feature/table component
  src/App.vue
  src/assets/index.css
  src/components/Pagination/index.vue
  src/components/checkbox/index.vue
  src/components/dropdown/index.vue
  src/components/groupButton/index.vue
  src/components/icons/DotHorizontal.vue
  src/components/icons/Selector.vue
  src/components/input/index.vue
  src/components/table/index.vue
Labels: New Feature

#79 feat(autosearch): nodata slot
  src/components/autosearch/index.vue
Labels: Improvement

#84 dailog width in px
  src/components/dialog/index.vue
Labels: Improvement

#95 added comments in the select dropdown .vue file
  src/components/select/index.vue
Labels: bug

#96 story for table
  src/App.vue
  src/components/table/Table.stories.js
  src/components/table/index.vue
Labels: Improvement
