Repository desk-design-system/d2s, pull requests merged in 2023-08, with the labels that each got.

#186 Input button
  src/components/input/index.vue
Labels: Improvement

#176 Fancy accordion
  src/components/AccordionTab/AccordionTab.stories.js
Labels: New Feature

#172 Storybook code snippet
  package-lock.json
  src/components/Navlinks/navigation.stories.js
  src/components/Pagination/Pagination.stories.js
  src/components/SettingsBar/settings.stories.js
  src/components/Telinput/TelInput.stories.js
  src/components/Tree/tree.stories.js
  src/components/alerts/Alert.stories.js
  src/components/autosearch/Autosearch.stories.js
  src/components/avatars/Avatar.stories.js
  src/components/badges/Badges.stories.js
  src/components/breadcrumbs/Breadcrumbs.stories.js
  src/components/buttons/Button.stories.js
  src/components/card/card.stories.js
  src/components/checkbox/Checkbox.stories.js
  src/components/divider/Divider.stories.js
  src/components/drawer/Drawer.stories.js
  src/components/dropdown/Dropdown.stories.js
  src/components/groupButton/groupButton.stories.js
  src/components/input/Input.stories.js
  src/components/radiobutton/Radio.stories.js
  src/components/rating/Rating.stories.js
  src/components/select/Select.stories.js
  src/components/stepper/Stepper.stories.js
  src/components/table/Table.stories.js
  src/components/table/index.vue
  src/components/textarea/Textarea.stories.js
  src/components/toggle/Toggle.stories.js
  src/components/tooltip/Tooltip.stories.js
  src/components/typography/Typography.stories.js
Labels: New Feature

#189 fix: table icon issue fix
  src/components/svgIcon/index.vue
Labels: New Feature, Improvement

#203 Settings and button
  src/components/SettingsBar/index.vue
  src/components/buttons/index.vue
Labels: bug, Improvement

#208 button conflict fixes
  src/components/buttons/index.vue
Labels: bug, Improvement

#213 Bugfix/slight tooltip dialog issues
  src/components/dialog/index.vue
  src/components/select/index.vue
  src/components/svgIcon/index.vue
  src/components/tooltip/Tooltip.stories.js
  src/components/tooltip/index.vue
Labels: Improvement

#212 Desk design fixes
  src/App.vue
  src/components/Accordion/accordion.stories.js
  src/components/Accordion/index.vue
  src/components/AccordionTab/AccordionTab.stories.js
  src/components/AccordionTab/index.vue
  src/components/InnerHeader/index.vue
  src/components/MessageBox/MessageBox.stories.js
  src/components/MessageBox/MessageBoxUi.vue
  src/components/MessageBox/index.js
  src/components/Navlinks/navigation.stories.js
  src/components/Pagination/Pagination.stories.js
  src/components/Pagination/index.vue
  src/components/SettingsBar/settings.stories.js
  src/components/Telinput/TelInput.stories.js
  src/components/Tree/Actions.vue
  src/components/Tree/index.vue
  src/components/Tree/listItems.vue
  src/components/Tree/tree.stories.js
  src/components/alerts/Alert.stories.js
  src/components/autosearch/Autosearch.stories.js
  src/components/avatars/Avatar.stories.js
  src/components/avatars/index.vue
  src/components/badges/Badges.stories.js
  src/components/badges/index.vue
  src/components/breadcrumbs/Breadcrumbs.stories.js
  src/components/buttons/Button.stories.js
  src/components/card/card.stories.js
  src/components/checkbox/Checkbox.stories.js
  src/components/checkbox/index.vue
  src/components/dialog/Dialog.stories.js
  src/components/divider/Divider.stories.js
  src/components/drawer/Drawer.stories.js
  src/components/drawer/index.vue
  src/components/dropdown/Dropdown.stories.js
  src/components/groupButton/groupButton.stories.js
  src/components/icons/Curved.vue
  src/components/icons/GripVerticle.vue
  src/components/icons/Pencil.vue
  src/components/icons/Plus.vue
  src/components/icons/Selector.vue
  src/components/icons/SelectorDown.vue
  src/components/icons/SelectorUp.vue
  src/components/icons/SquareDot.vue
  src/components/icons/Trash.vue
  src/components/input/Input.stories.js
  src/components/input/index.vue
  src/components/notification/Notification.stories.js
  src/components/notification/notificationUI.vue
  src/components/radiobutton/Radio.stories.js
  src/components/rating/Rating.stories.js
  src/components/rating/index.vue
  src/components/select/Select.stories.js
  src/components/stepper/Stepper.stories.js
  src/components/table/Table.stories.js
  src/components/table/hoverRow.vue
  src/components/table/index.vue
  src/components/textarea/Textarea.stories.js
  src/components/toggle/Toggle.stories.js
  src/components/tooltip/Tooltip.stories.js
  src/components/typography/Typography.stories.js
Labels: bug, Improvement

#218 feat: add gradient and slot changes
  src/components/Accordion/index.vue
  src/components/AccordionTab/AccordionTab.stories.js
  src/components/AccordionTab/index.vue
Labels: Improvement

#217 Badge design fixes
  src/components/badges/index.vue
  src/components/buttons/index.vue
  src/components/table/index.vue
Labels: Improvement

#216 z-index fixes
  src/components/table/index.vue
  src/components/tabs/Tabs.stories.js
  src/components/tabs/index.vue
Labels: Improvement

#219 Alert revamp
  src/components/alerts/Alert.stories.js
  src/components/alerts/index.vue
Labels: Improvement

#220 Dialog story updation
  src/App.vue
  src/components/buttons/Button.stories.js
  src/components/dialog/Dialog.stories.js
  src/components/dialog/index.vue
  src/components/drawer/Drawer.stories.js
  src/components/drawer/index.vue
  src/components/topbar/Topbar.stories.js
  src/components/typography/Typography.stories.js
Labels: Improvement

#221 build issue fixes
  src/App.vue
  src/components/drawer/Drawer.stories.js
Labels: bug, Improvement

#223 input button fixes
  src/components/buttons/index.vue
  src/components/input/index.vue
Labels: Improvement

#225 badge changes done
  src/components/buttons/index.vue
  src/components/tabs/Tabs.stories.js
  src/components/tabs/index.vue
Labels: Improvement

#224 fix: dropdown icon issue on validation is fixed
  src/components/select/index.vue
Labels: Improvement

#227 fix: add default icon
  src/components/AccordionTab/AccordionTab.stories.js
  src/components/svgIcon/index.vue
Labels: Improvement
