Repository desk-design-system/d2s, pull requests merged in 2023-07, with the labels that each got.

#139 feat(input):add label slot
  src/components/input/index.vue
Labels: bug, Improvement

#138 group-action-mrgin-fixes
  src/components/table/hoverRow.vue
Labels: Improvement

#137 group button story fixes
  src/components/groupButton/groupButton.stories.js
Labels: bug, Improvement

#136 fix: tooltip imported in component.js file
  src/components/components.js
Labels: bug, Improvement

#135 done
  src/components/input/index.vue
Labels: New Feature

#133 Button fixes
  src/App.vue
  src/components/buttons/Button.stories.js
  src/components/buttons/index.vue
Labels: Improvement

#143 message box fixes
  src/components/MessageBox/MessageBox.stories.js
  src/components/MessageBox/MessageBoxUi.vue
  src/components/MessageBox/index.js
  src/components/index.js
Labels: Improvement

#151 slot to add custom content in thead
  src/components/table/index.vue
Labels: Improvement

#149 button settlement according to new design
  src/App.vue
  src/components/buttons/index.vue
Labels: Improvement

#154 input-fixes
  src/App.vue
  src/components/input/index.vue
Labels: bug, Improvement

#155 Input fixes
  src/App.vue
  src/components/input/index.vue
Labels: bug, Improvement

#158 add classes in header ,content and footer and resolve issue scroll
  src/components/dialog/Dialog.stories.js
  src/components/dialog/index.vue
Labels: Improvement

#156 feat(icons): add icon gallery
  package-lock.json
  src/components/IconsGallery/IconsGallery.stories.js
  src/components/IconsGallery/index.vue
  src/components/select/index.vue
Labels: New Feature

#159 border color fixed
  src/App.vue
  src/components/input/index.vue
Labels: Improvement

#161 designing issue fixed
  src/components/Tree/listItems.vue
  src/components/icons/SquareMinus.vue
  src/components/icons/SquarePlus.vue
  storybook-static/favicon.ico
  storybook-static/project.json
  storybook-static/stories.json
Labels: Improvement

#165 button text fixes
  src/components/Tree/Actions.vue
  src/components/Tree/index.vue
Labels: bug

#166 fix(icons-gallery): fix icons not display
  src/components/IconsGallery/index.vue
Labels: bug

#168 feat: disable prop is set on select component
  src/components/select/Select.stories.js
  src/components/select/index.vue
Labels: New Feature, Improvement

#167 changes implemented
  src/App.vue
  src/components/SettingsBar/index.vue
  src/components/SettingsBar/settings.stories.js
  src/components/buttons/index.vue
  src/components/input/index.vue
Labels: Improvement

#169 button and scroll fixes
  src/components/SettingsBar/index.vue
  src/components/SettingsBar/settings.stories.js
  src/components/buttons/index.vue
Labels: Improvement

#171 alert and pagination styling
  src/components/Pagination/index.vue
  src/components/alerts/index.vue
Labels: Improvement

#170 padding fixes
  src/components/MessageBox/MessageBoxUi.vue
  src/components/Telinput/index.vue
Labels: bug
